# Generated by Django 5.1.6 on 2025-04-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bbdd', '0002_alter_prestamos_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
